// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJLPQ3ITuxQZg0-PkaZKpA3EdONyu6i0s',
    appId: '1:1090021950067:web:9a90a62cb274c10395a006',
    messagingSenderId: '1090021950067',
    projectId: 'pokedex-cf849',
    authDomain: 'pokedex-cf849.firebaseapp.com',
    storageBucket: 'pokedex-cf849.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQVXmvVok86bRU8YXO4_YdmUlJdY0fmEg',
    appId: '1:1090021950067:android:177f0bf587430f4395a006',
    messagingSenderId: '1090021950067',
    projectId: 'pokedex-cf849',
    storageBucket: 'pokedex-cf849.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSOEs2IxlJv13Fq_AJTt1zmgKbfywiYrI',
    appId: '1:1090021950067:ios:0e86e6e8c66b8f3495a006',
    messagingSenderId: '1090021950067',
    projectId: 'pokedex-cf849',
    storageBucket: 'pokedex-cf849.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSOEs2IxlJv13Fq_AJTt1zmgKbfywiYrI',
    appId: '1:1090021950067:ios:0e86e6e8c66b8f3495a006',
    messagingSenderId: '1090021950067',
    projectId: 'pokedex-cf849',
    storageBucket: 'pokedex-cf849.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJLPQ3ITuxQZg0-PkaZKpA3EdONyu6i0s',
    appId: '1:1090021950067:web:be09b3d1e6d3a3b695a006',
    messagingSenderId: '1090021950067',
    projectId: 'pokedex-cf849',
    authDomain: 'pokedex-cf849.firebaseapp.com',
    storageBucket: 'pokedex-cf849.firebasestorage.app',
  );
}
